/**
 * Centralized localStorage key constants.
 * Use these when reading/writing so keys stay consistent and auditable.
 */
export const STORAGE_KEYS = {
  NOTES: 'notes',
  NOTES_VIEW_PREFS: 'notesViewPrefs',
  SIDEBAR_NAV: 'sidebarNav',
  DARK_MODE: 'darkMode',
  DASHBOARD_SYMBOLS: 'dashboardSymbols',
  DASHBOARD_WORLD_CLOCKS: 'dashboardWorldClocks',
  DASHBOARD_SECTION_ORDER: 'dashboardSectionOrder',
  REFRESH_INTERVAL: 'refreshInterval',
  DEFAULT_SYMBOLS: 'defaultSymbols',
  NOTIFICATION_SETTINGS: 'notificationSettings',
  GENERAL_SETTINGS: 'generalSettings',
  APPEARANCE_SETTINGS: 'appearanceSettings',
  DATA_SETTINGS: 'dataSettings',
  ACCESSIBILITY_SETTINGS: 'accessibilitySettings',
  API_KEYS: 'apiKeys',
  USER_PROFILE: 'userProfile',
  SAVED_PROJECTIONS: 'savedProjections',
  PROJECTION_RECENT_SEARCHES: 'projectionRecentSearches',
  PROJECTION_LAST_SYMBOL: 'projectionLastSymbol',
  PROJECTION_LAST_INTERVAL: 'projectionLastInterval',
  TRADING_RECENT_SEARCHES: 'tradingRecentSearches',
  TRADING_LAST_SYMBOL: 'tradingLastSymbol',
  TRADING_LAST_INTERVAL: 'tradingLastInterval',
  TRADING_CHART_TYPE: 'tradingChartType',
  PREFERRED_API: 'preferredApi',
  BUDGET_CATEGORIES: 'budgetTracker_categories',
  BUDGET_BUDGETS: 'budgetTracker_budgets',
  BUDGET_REMINDERS: 'budgetTracker_reminders',
  BTC_MINER_ADDRESS: 'btc_miner_address',
  BTC_MINER_CONNECTION: 'btc_miner_connection',
  FIB_SYMBOL: 'fibStuffSymbol',
  FIB_PRECISION: 'fibStuffPrecision',
  DELETED_MONITORS: 'deletedMonitors',
  SAVED_PROJECTIONS_STORAGE: 'savedProjectionsStorage',
  ANNOUNCEMENT_DISMISSED: 'announcement_dismissed',
  STABILIZED_MODELS: 'stabilizedModels',
  CME_LAST_SYMBOL: 'cmeLastSymbol',
};
