/**
 * Centralized localStorage key constants.
 * Use these when reading/writing so keys stay consistent and auditable.
 */
export const STORAGE_KEYS = {
  SIDEBAR_NAV: 'sidebarNav',
  DARK_MODE: 'darkMode',
  DASHBOARD_SYMBOLS: 'dashboardSymbols',
  DASHBOARD_WORLD_CLOCKS: 'dashboardWorldClocks',
  DASHBOARD_SECTION_ORDER: 'dashboardSectionOrder',
  REFRESH_INTERVAL: 'refreshInterval',
  DEFAULT_SYMBOLS: 'defaultSymbols',
  NOTIFICATION_SETTINGS: 'notificationSettings',
  GENERAL_SETTINGS: 'generalSettings',
  APPEARANCE_SETTINGS: 'appearanceSettings',
  DATA_SETTINGS: 'dataSettings',
  ACCESSIBILITY_SETTINGS: 'accessibilitySettings',
  API_KEYS: 'apiKeys',
  USER_PROFILE: 'userProfile',
  TRADING_RECENT_SEARCHES: 'tradingRecentSearches',
  TRADING_LAST_SYMBOL: 'tradingLastSymbol',
  TRADING_LAST_INTERVAL: 'tradingLastInterval',
  TRADING_CHART_TYPE: 'tradingChartType',
  PREFERRED_API: 'preferredApi',
  BTC_MINER_ADDRESS: 'btc_miner_address',
  BTC_MINER_CONNECTION: 'btc_miner_connection',
  BTC_MINER_SEARCH_MODE: 'btc_miner_search_mode',
  BTC_MINER_AUTO_ROUND: 'btc_miner_auto_round',
  FIB_SYMBOL: 'fibStuffSymbol',
  FIB_PRECISION: 'fibStuffPrecision',
  DELETED_MONITORS: 'deletedMonitors',
  ANNOUNCEMENT_DISMISSED: 'announcement_dismissed',
  STABILIZED_MODELS: 'stabilizedModels',
  CHECKLIST_HISTORY: 'checklist_history',
  CHECKLIST_CUSTOM_ITEMS: 'checklist_customItems',
  CHECKLIST_LABEL_OVERRIDES: 'checklist_labelOverrides',
  CHECKLIST_HISTORY_META: 'checklist_historyMeta',
  CHECKLIST_CATEGORY_LABEL_OVERRIDES: 'checklist_categoryLabelOverrides',
  CHECKLIST_HIDDEN_CATEGORY_IDS: 'checklist_hiddenCategoryIds',
  CHECKLIST_USER_CATEGORIES: 'checklist_userCategories',
};
